// app/utils/teamNamesES.ts

/* ---------------------------------------------------------
   TRADUCCIONES DE EQUIPOS, PAÍSES Y LIGAS AL ESPAÑOL
   Si una clave no existe, en la app se usa el nombre original.
---------------------------------------------------------- */

export const TEAM_NAME_ES: Record<string, string> = {
  /* ===========================
        ESPAÑA – LALIGA
  ============================ */
  "Real Madrid": "Real Madrid",
  "Barcelona": "Barcelona",
  "Atlético Madrid": "Atlético de Madrid",
  "Atletico Madrid": "Atlético de Madrid",
  "Sevilla": "Sevilla",
  "Real Betis": "Real Betis",
  "Real Sociedad": "Real Sociedad",
  "Athletic Club": "Athletic Club",
  "Ath Bilbao": "Athletic Club",
  "Valencia": "Valencia",
  "Villarreal": "Villarreal",
  "Osasuna": "Osasuna",
  "Celta Vigo": "Celta de Vigo",
  "Celta de Vigo": "Celta de Vigo",
  "Getafe": "Getafe",
  "Rayo Vallecano": "Rayo Vallecano",
  "Granada CF": "Granada",
  "Alavés": "Alavés",
  "Alaves": "Alavés",
  "Las Palmas": "Las Palmas",
  "Leganes": "Leganés",
  "Mallorca": "Mallorca",
  "Girona": "Girona",
  "Cadiz": "Cádiz",
  "Cádiz CF": "Cádiz",
  "Espanyol": "Espanyol",

  /* ===========================
        INGLATERRA – PREMIER
  ============================ */
  "Manchester City": "Manchester City",
  "Manchester Utd": "Manchester United",
  "Manchester United": "Manchester United",
  "Liverpool": "Liverpool",
  "Arsenal": "Arsenal",
  "Chelsea": "Chelsea",
  "Tottenham": "Tottenham",
  "Newcastle": "Newcastle",
  "Newcastle United": "Newcastle",
  "Aston Villa": "Aston Villa",
  "West Ham": "West Ham",
  "West Ham United": "West Ham",
  "Everton": "Everton",
  "Brighton": "Brighton",
  "Brighton & Hove Albion": "Brighton",
  "Wolves": "Wolves",
  "Wolverhampton": "Wolves",
  "Nottingham Forest": "Nottingham Forest",
  "Crystal Palace": "Crystal Palace",
  "Brentford": "Brentford",
  "Fulham": "Fulham",
  "Bournemouth": "Bournemouth",
  "Leicester": "Leicester City",
  "Leicester City": "Leicester City",
  "Leeds": "Leeds United",
  "Leeds United": "Leeds United",
  "Southampton": "Southampton",
  "Burnley": "Burnley",
  "Sheffield Utd": "Sheffield United",
  "Sheffield United": "Sheffield United",

  /* ===========================
        ITALIA – SERIE A
  ============================ */
  "Juventus": "Juventus",
  "Inter": "Inter de Milán",
  "Inter Milan": "Inter de Milán",
  "AC Milan": "AC Milan",
  "Milan": "AC Milan",
  "Napoli": "Napoli",
  "Roma": "Roma",
  "Lazio": "Lazio",
  "Atalanta": "Atalanta",
  "Fiorentina": "Fiorentina",
  "Torino": "Torino",
  "Udinese": "Udinese",
  "Sassuolo": "Sassuolo",
  "Genoa": "Génova",
  "Genoa CFC": "Génova",
  "Bologna": "Bolonia",
  "Bologna FC 1909": "Bolonia",
  "Cagliari": "Cagliari",
  "Empoli": "Empoli",
  "Lecce": "Lecce",
  "Verona": "Verona",
  "Hellas Verona": "Hellas Verona",
  "Salernitana": "Salernitana",
  "Monza": "Monza",

  /* ===========================
        ALEMANIA – BUNDESLIGA
  ============================ */
  "Bayern Munich": "Bayern de Múnich",
  "Bayern München": "Bayern de Múnich",
  "Borussia Dortmund": "Borussia Dortmund",
  "RB Leipzig": "RB Leipzig",
  "Bayer Leverkusen": "Bayer Leverkusen",
  "Eintracht Frankfurt": "Eintracht Frankfurt",
  "Union Berlin": "Unión Berlín",
  "SC Freiburg": "Friburgo",
  "Freiburg": "Friburgo",
  "VfB Stuttgart": "Stuttgart",
  "Stuttgart": "Stuttgart",
  "Wolfsburg": "Wolfsburgo",
  "VfL Wolfsburg": "Wolfsburgo",
  "Mainz": "Mainz",
  "FSV Mainz 05": "Mainz",
  "Werder Bremen": "Werder Bremen",
  "Hoffenheim": "Hoffenheim",
  "TSG Hoffenheim": "Hoffenheim",
  "Augsburg": "Augsburgo",
  "FC Augsburg": "Augsburgo",
  "Köln": "Colonia",
  "FC Koln": "Colonia",
  "Bochum": "Bochum",
  "Heidenheim": "Heidenheim",
  "Darmstadt": "Darmstadt",

  /* ===========================
        FRANCIA – LIGUE 1
  ============================ */
  "Paris Saint Germain": "PSG",
  "Paris Saint-Germain": "PSG",
  "PSG": "PSG",
  "Marseille": "Marsella",
  "Olympique Marseille": "Marsella",
  "Lyon": "Lyon",
  "Olympique Lyonnais": "Lyon",
  "Lille": "Lille",
  "Monaco": "Mónaco",
  "Nice": "Niza",
  "Rennes": "Rennes",
  "Nantes": "Nantes",
  "Lens": "Lens",
  "Montpellier": "Montpellier",
  "Bordeaux": "Burdeos",
  "Toulouse": "Toulouse",
  "Reims": "Reims",
  "Strasbourg": "Estrasburgo",
  "Saint Etienne": "Saint-Étienne",
  "Saint-Étienne": "Saint-Étienne",

  /* ===========================
        PORTUGAL – LIGA
  ============================ */
  "Benfica": "Benfica",
  "Porto": "Oporto",
  "FC Porto": "Oporto",
  "Sporting CP": "Sporting Lisboa",
  "Sporting Lisbon": "Sporting Lisboa",
  "Braga": "Braga",
  "SC Braga": "Braga",

  /* ===========================
        PAÍSES BAJOS – EREDIVISIE
  ============================ */
  "Ajax": "Ajax",
  "PSV Eindhoven": "PSV",
  "PSV": "PSV",
  "Feyenoord": "Feyenoord",
  "AZ Alkmaar": "AZ Alkmaar",
  "AZ": "AZ Alkmaar",

  /* ===========================
        ARGENTINA – PRIMERA
  ============================ */
  "Boca Juniors": "Boca Juniors",
  "River Plate": "River Plate",
  "Racing Club": "Racing Club",
  "Independiente": "Independiente",
  "San Lorenzo": "San Lorenzo",
  "Velez Sarsfield": "Vélez Sarsfield",
  "Vélez Sarsfield": "Vélez Sarsfield",
  "Newells Old Boys": "Newell's Old Boys",
  "Newell's Old Boys": "Newell's Old Boys",
  "Rosario Central": "Rosario Central",
  "Estudiantes L.P.": "Estudiantes de La Plata",
  "Estudiantes La Plata": "Estudiantes de La Plata",
  "Huracan": "Huracán",
  "Huracán": "Huracán",
  "Lanus": "Lanús",
  "Lanús": "Lanús",
  "Argentinos JRS": "Argentinos Juniors",
  "Argentinos Juniors": "Argentinos Juniors",
  "Talleres Cordoba": "Talleres de Córdoba",
  "Talleres de Córdoba": "Talleres de Córdoba",

  /* ===========================
        BRASIL – BRASILEIRÃO
  ============================ */
  "Flamengo": "Flamengo",
  "Palmeiras": "Palmeiras",
  "Corinthians": "Corinthians",
  "Sao Paulo": "São Paulo",
  "São Paulo": "São Paulo",
  "Fluminense": "Fluminense",
  "Gremio": "Grêmio",
  "Grêmio": "Grêmio",
  "Internacional": "Internacional",
  "Botafogo": "Botafogo",
  "Cruzeiro": "Cruzeiro",
  "Atletico Mineiro": "Atlético Mineiro",
  "Atlético Mineiro": "Atlético Mineiro",
  "Santos": "Santos",
  "Athletico Paranaense": "Athletico Paranaense",
  "Bahia": "Bahía",
  "Fortaleza": "Fortaleza",
  "Vasco DA Gama": "Vasco da Gama",
  "Vasco da Gama": "Vasco da Gama",

  /* ===========================
        MÉXICO – LIGA MX
  ============================ */
  "Club America": "América",
  "América": "América",
  "Chivas Guadalajara": "Chivas",
  "Guadalajara Chivas": "Chivas",
  "Pumas UNAM": "Pumas",
  "Cruz Azul": "Cruz Azul",
  "Monterrey": "Monterrey",
  "Tigres UANL": "Tigres",
  "Santos Laguna": "Santos Laguna",
  "Toluca": "Toluca",
  "Pachuca": "Pachuca",
  "León": "León",
  "Leon": "León",

  /* ===========================
        PERÚ
  ============================ */
  "Alianza Lima": "Alianza Lima",
  "Universitario de Deportes": "Universitario",
  "Universitario": "Universitario",
  "Sporting Cristal": "Sporting Cristal",
  "Melgar": "Melgar",

  /* ===========================
        MLS (PRINCIPALES)
  ============================ */
  "Inter Miami": "Inter Miami",
  "LA Galaxy": "LA Galaxy",
  "Los Angeles FC": "Los Angeles FC",
  "Seattle Sounders": "Seattle Sounders",
  "Atlanta United": "Atlanta United",
  "New York City FC": "New York City FC",
  "New York Red Bulls": "New York Red Bulls",
  "Toronto FC": "Toronto FC",

  /* ===========================
        SELECCIONES (FIFA)
        (TU LISTA + AJUSTES)
  ============================ */
  // EUROPA (UEFA)
  "Spain": "España",
  "France": "Francia",
  "Germany": "Alemania",
  "Italy": "Italia",
  "Portugal": "Portugal",
  "Netherlands": "Países Bajos",
  "Belgium": "Bélgica",
  "England": "Inglaterra",
  "Croatia": "Croacia",
  "Serbia": "Serbia",
  "Switzerland": "Suiza",
  "Austria": "Austria",
  "Denmark": "Dinamarca",
  "Norway": "Noruega",
  "Sweden": "Suecia",
  "Finland": "Finlandia",
  "Poland": "Polonia",
  "Czech Republic": "República Checa",
  "Slovakia": "Eslovaquia",
  "Slovenia": "Eslovenia",
  "Hungary": "Hungría",
  "Greece": "Grecia",
  "Turkey": "Turquía",
  "Romania": "Rumanía",
  "Bulgaria": "Bulgaria",
  "Albania": "Albania",
  "North Macedonia": "Macedonia del Norte",
  "Bosnia and Herzegovina": "Bosnia y Herzegovina",
  "Montenegro": "Montenegro",
  "Georgia": "Georgia",
  "Armenia": "Armenia",
  "Azerbaijan": "Azerbaiyán",
  "Ukraine": "Ucrania",
  "Russia": "Rusia",
  "Wales": "Gales",
  "Scotland": "Escocia",
  "Ireland": "Irlanda",
  "Northern Ireland": "Irlanda del Norte",
  "Iceland": "Islandia",
  "Estonia": "Estonia",
  "Latvia": "Letonia",
  "Lithuania": "Lituania",
  "Luxembourg": "Luxemburgo",
  "Cyprus": "Chipre",
  "Malta": "Malta",
  "Kosovo": "Kosovo",
  "Faroe Islands": "Islas Feroe",
  "San Marino": "San Marino",
  "Andorra": "Andorra",
  "Liechtenstein": "Liechtenstein",

  // AMÉRICA (CONMEBOL + CONCACAF)
  "Argentina": "Argentina",
  "Brazil": "Brasil",
  "Uruguay": "Uruguay",
  "Chile": "Chile",
  "Peru": "Perú",
  "Colombia": "Colombia",
  "Paraguay": "Paraguay",
  "Bolivia": "Bolivia",
  "Venezuela": "Venezuela",
  "Ecuador": "Ecuador",
  "Mexico": "México",
  "United States": "Estados Unidos",
  "Canada": "Canadá",
  "Costa Rica": "Costa Rica",
  "Honduras": "Honduras",
  "El Salvador": "El Salvador",
  "Panama": "Panamá",
  "Guatemala": "Guatemala",
  "Nicaragua": "Nicaragua",
  "Haiti": "Haití",
  "Cuba": "Cuba",
  "Jamaica": "Jamaica",
  "Trinidad and Tobago": "Trinidad y Tobago",
  "Dominican Republic": "República Dominicana",

  // ASIA (AFC)
  "Japan": "Japón",
  "South Korea": "Corea del Sur",
  "North Korea": "Corea del Norte",
  "China PR": "China",
  "Saudi Arabia": "Arabia Saudita",
  "Qatar": "Catar",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  "Iran": "Irán",
  "Iraq": "Irak",
  "Syria": "Siria",
  "Lebanon": "Líbano",
  "Jordan": "Jordania",
  "Oman": "Omán",
  "Kuwait": "Kuwait",
  "Bahrain": "Baréin",
  "India": "India",
  "Pakistan": "Pakistán",
  "Afghanistan": "Afganistán",
  "Vietnam": "Vietnam",
  "Thailand": "Tailandia",
  "Indonesia": "Indonesia",
  "Malaysia": "Malasia",
  "Philippines": "Filipinas",
  "Singapore": "Singapur",
  "Uzbekistan": "Uzbekistán",
  "Kazakhstan": "Kazajistán",
  "Kyrgyzstan": "Kirguistán",
  "Tajikistan": "Tayikistán",
  "Turkmenistan": "Turkmenistán",
  "Myanmar": "Myanmar",
  "Bangladesh": "Bangladés",
  "Mongolia": "Mongolia",
  "Nepal": "Nepal",
  "Sri Lanka": "Sri Lanka",
  "Hong Kong": "Hong Kong",

  // ÁFRICA (CAF)
  "Morocco": "Marruecos",
  "Algeria": "Argelia",
  "Tunisia": "Túnez",
  "Egypt": "Egipto",
  "Senegal": "Senegal",
  "Nigeria": "Nigeria",
  "Ghana": "Ghana",
  "Cameroon": "Camerún",
  "Ivory Coast": "Costa de Marfil",
  "Mali": "Malí",
  "Burkina Faso": "Burkina Faso",
  "Guinea": "Guinea",
  "Guinea-Bissau": "Guinea-Bisáu",
  "Cape Verde": "Cabo Verde",
  "South Africa": "Sudáfrica",
  "Angola": "Angola",
  "Zimbabwe": "Zimbabue",
  "Zambia": "Zambia",
  "Mozambique": "Mozambique",
  "Uganda": "Uganda",
  "Kenya": "Kenia",
  "Tanzania": "Tanzania",
  "Namibia": "Namibia",
  "Botswana": "Botsuana",
  "Benin": "Benín",
  "Togo": "Togo",
  "DR Congo": "República Democrática del Congo",
  "Congo": "Congo",
  "Chad": "Chad",
  "Niger": "Níger",
  "Central African Republic": "República Centroafricana",
  "Burundi": "Burundi",
  "Rwanda": "Ruanda",
  "Ethiopia": "Etiopía",
  "Eritrea": "Eritrea",
  "Somalia": "Somalia",
  "Sudan": "Sudán",
  "South Sudan": "Sudán del Sur",
  "Gambia": "Gambia",
  "Liberia": "Liberia",
  "Sierra Leone": "Sierra Leona",
  "Madagascar": "Madagascar",
  "Mauritania": "Mauritania",
  "Mauritius": "Mauricio",
  "Seychelles": "Seychelles",
  "Comoros": "Comoras",

  // OCEANÍA (OFC)
  "Australia": "Australia",
  "New Zealand": "Nueva Zelanda",
  "Fiji": "Fiyi",
  "Solomon Islands": "Islas Salomón",
  "Vanuatu": "Vanuatu",
  "Samoa": "Samoa",
  "Tahiti": "Tahití",
  "Tonga": "Tonga",
  "Papua New Guinea": "Papúa Nueva Guinea",
};

/* ---------------------------------------------------------
        PAISES EN ESPAÑOL
---------------------------------------------------------- */
export const COUNTRY_NAME_ES: Record<string, string> = {
  "England": "Inglaterra",
  "Spain": "España",
  "Germany": "Alemania",
  "France": "Francia",
  "Italy": "Italia",
  "Portugal": "Portugal",
  "Netherlands": "Países Bajos",
  "Argentina": "Argentina",
  "Brazil": "Brasil",
  "Mexico": "México",
  "Peru": "Perú",
  "Chile": "Chile",
  "Colombia": "Colombia",
  "United States": "Estados Unidos",
  "Canada": "Canadá",
  "Qatar": "Catar",
  "Saudi Arabia": "Arabia Saudita",
};

/* ---------------------------------------------------------
        LIGAS EN ESPAÑOL
---------------------------------------------------------- */
export const LEAGUE_NAME_ES: Record<string, string> = {
  "La Liga": "LaLiga (España)",
  "La Liga 2": "LaLiga 2 (España)",
  "Premier League": "Premier League (Inglaterra)",
  "Championship": "Championship (Inglaterra)",
  "Serie A": "Serie A (Italia)",
  "Bundesliga": "Bundesliga (Alemania)",
  "Ligue 1": "Ligue 1 (Francia)",
  "Primeira Liga": "Primeira Liga (Portugal)",
  "Eredivisie": "Eredivisie (Países Bajos)",
  "Copa del Rey": "Copa del Rey (España)",
  "FA Cup": "FA Cup (Inglaterra)",
  "Coppa Italia": "Copa Italia",
  "DFB Pokal": "Copa de Alemania",
  "UEFA Champions League": "Liga de Campeones UEFA",
  "UEFA Europa League": "Liga Europa UEFA",
  "UEFA Europa Conference League": "Conference League UEFA",
  "World Cup - Qualification Europe": "Clasificación Mundial — Europa",
  "World Cup - Qualification South America":
    "Clasificación Mundial — Sudamérica",
};
